locale      : "fr-FR"
site_theme  : "default"
title       : "G B — Mathématiques"
title_separator: "-"
name        : &name "G B"
description : &description "Portfolio académique — L3 Mathématiques (Sorbonne Université)"
url         : "https://116500ln.github.io"
baseurl     : ""
repository  : "116500LN/116500LN.github.io"

author:
  avatar   : "profile.png"
  name     : "G B"
  bio      : "some maths stuff"
  location : "Paris, France - Geneva, Switzerland"
  employer : "BS in Math — Sorbonne University"
  email    : 

include:
  - _pages
  - files

words_per_minute: 160
future: true
read_more: "disabled"
timezone: Europe/Paris

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Make the left nav appear everywhere by default
defaults:
  - scope: { path: "", type: pages }
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"
  - scope: { path: "", type: posts }
    values:
      layout: single
      author_profile: true
      comments: false
      sidebar:
        nav: "docs"

permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
